name = "DGGSExplorer"
uuid = "07de296f-62fe-4442-9246-51e3bb826ad2"
authors = ["Daniel Loos"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
